name: flutter_moments
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.15.6
  scoped_model: ^1.0.1
  carousel_slider: ^1.3.0
  page_transition: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  fonts:
  - family: Rubik
    fonts:
    - asset: fonts/Rubik-Regular.ttf
    - asset: fonts/Rubik-Medium.ttf
  - family: DancingScript
    fonts:
    - asset: fonts/DancingScript-Regular.otf
  - family: DINOT
    fonts:
    - asset: fonts/DINOT-Regular.ttf   
    - asset: fonts/DINOT-Bold.otf   
      weight: 700
  - family: Cookie
    fonts:
    - asset: fonts/Cookie-Regular.ttf       
  assets:
    - assets/home_bg.png
    - assets/main_bg.png
    - assets/LOGO.png
    - assets/pic1.jpg
    - assets/pic2.jpg
    - assets/pic3.jpg
    - assets/pic4.jpg
    - assets/pic5.jpg 
    - assets/menu_form.png
    - assets/menu_list.png
    - assets/menu_richList.png
    - assets/logout.png    
